### PR TITLE
Docs: Introduce badges to make readme look more cool

### PR DESCRIPTION
**Pull request by literat**

### CODE REVIEW

**Comment by OndraM** [comment]
Is it just me, or is the text in the official badge overflowing? :monocle_face: 
obrazek

**Comment by literat** [comment]
@OndraM Works for me :D
Screenshot 2021-11-01 at 12 57 32

You are on Linux, right? 🤔

**Comment by OndraM** [comment]
> You are on Linux, right? :thinking:

Yes 🤷 :penguin:

**Review by OndraM — APPROVED** [review]
Nevermind, it is caused by mine Firefox font settings (I force minimal font size to 12px, while this needs 11 px :) ).

**Pull request merged**
