### PR TITLE
Deps: Update eslint to latest ^8 version

### PR DESCRIPTION
**Pull request by OndraM**

### CODE REVIEW

**Comment by literat** [comment]
I think you should also instruct renovate via configuration file to not upgrade ESLint to v9.

**Review by literat — APPROVED** [review]

**Comment by OndraM** [comment]
> I think you should also instruct renovate via configuration file to not upgrade ESLint to v9.

Yup, good point, I wanted to do this right after the dependency backlog is cleared a bit, but I may add into this PR :)

**Comment by OndraM** [comment]
@literat Renovate bot config added :)

**Review by literat — APPROVED** [review]

**Comment by literat** [comment]
> @literat Renovate bot config added :)

Nice, thanks :-)

**Pull request merged**
